routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::group(['middleware' => 'admin'], function() {
    Route::get('/admin', 'AdminController@index')->name('admin')->middleware('admin');
    Route::get('/operator', 'OperatorController@index')->name('operator')->middleware('operator');
    Route::get('/lapor', 'LaporController@index')->name('lapor')->middleware('lapor');

    Route::get('/', 'HomeController@index')->name('home');

    Route::resource("users", "UserController");

    Route::get('/subdistricts/trash', 'SubdistrictController@trash')->name('subdistricts.trash');
    Route::get('/subdistricts/{id}/restore', 'SubdistrictController@restore')->name('subdistricts.restore');
    Route::delete('/subdistricts/{id}/delete-permanent', 'SubdistrictController@deletePermanent')->name('subdistricts.delete-permanent');
    Route::get('/ajax/subdistricts/search', 'SubdistrictController@ajaxSearch');
    Route::resource("subdistricts", "SubdistrictController");

    Route::get('/cari', 'Select2Controller@loadData');
    Route::get('/villages/trash', 'VillageController@trash')->name('villages.trash');
    Route::get('/villages/{id}/restore', 'VillageController@restore')->name('villages.restore');
    Route::delete('/villages/{id}/delete-permanent', 'VillageController@deletePermanent')->name('villages.delete-permanent');
    Route::resource('villages', 'VillageController');

    Route::get('/floodreports/trash', 'FloodreportController@trash')->name('floodreports.trash');
    Route::get('/floodreports/{id}/restore', 'FloodreportController@restore')->name('floodreports.restore');
    Route::delete('/floodreports/{id}/delete-permanent', 'FloodreportController@deletePermanent')->name('floodreports.delete-permanent');
    Route::resource('floodreports', 'FloodreportController');

    Route::get('/helpreports/trash', 'HelpreportController@trash')->name('helpreports.trash');
    Route::get('/helpreports/{id}/restore', 'HelpreportController@restore')->name('helpreports.restore');
    Route::delete('/helpreports/{id}/delete-permanent', 'HelpreportController@deletePermanent')->name('helpreports.delete-permanent');
    Route::resource('helpreports', 'HelpreportController');

    Route::get('/floodhistories/trash', 'FloodhistoryController@trash')->name('floodhistories.trash');
    Route::get('/floodhistories/{id}/restore', 'FloodhistoryController@restore')->name('floodhistories.restore');
    Route::delete('/floodhistories/{id}/delete-permanent', 'FloodhistoryController@deletePermanent')->name('floodhistories.delete-permanent');
    Route::resource('floodhistories', 'FloodhistoryController');

    Route::get('/posts/trash', 'PostController@trash')->name('posts.trash');
    Route::get('/posts/{id}/restore', 'PostController@restore')->name('posts.restore');
    Route::delete('/posts/{id}/delete-permanent', 'PostController@deletePermanent')->name('posts.delete-permanent');
    Route::resource('posts', 'PostController');

    Route::get('/map/petabanjir', 'VisualisasiMapController@get_petabanjir');
    // Route::get('/map/rawanbanjir', 'VisualisasiMapController@get_rawanbanjir')->name('map.rawanbanjir');


    Route::resource('/districts', 'DistrictsController');
    Route::resource('/villages_district', 'VillagesDistrictController');
    Route::resource('/populations', 'PopulationsController');
    Route::resource('/landheights', 'LandheightsController');
    Route::resource('/histories', 'HistoriesController');
    Route::resource('/reservoirs', 'ReservoirsController');
    Route::resource('/procedures', 'ProceduresController');
    Route::resource('/rivers', 'RiversController');
    Route::resource('/weathers', 'WeathersController');
});

resources/views/villagesperingatan/create.blade.php
@extends('layouts.global')
@section('content')

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Tambah Data Desa</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{url ('/admin') }}">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('villages.index') }}">Data Desa</a></li>
                    <li class="breadcrumb-item active">Tambah Data Desa</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<section class="content">
    <div class="container-fluid">
        <form method="POST" action="{{route('villages.store')}}">
            <input type="hidden" name="_token" value="{{ csrf_token()}} ">
            <div class="form-group">
                <div class="row">
                    <label class="col-md-3">Nama Desa</label>
                    <div class="col-md-6">
                        <input type="text" name="title" class="form-control"/>
                    </div>
                </div>
                
                <div class="row mt-3">
                    <label class="col-md-3">Kecamatan</label>
                    <div class="col-md-6">
                        <select type="text" name="district_id" class="form-control">
                            <option value="">Pilih Kecamatan</option>
                            @foreach ($districts as $d)
                            <option value="{{ $d -> id}}">{{ $d -> title}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                
                <div class="row mt-3">
                    <label class="col-md-3">Longitude Desa</label>
                    <div class="col-md-6">
                        <input type="number" name="long_villages" class="form-control"/>
                    </div>
                </div>
                
                <div class="row mt-3">
                    <label class="col-md-3">Latitude Desa</label>
                    <div class="col-md-6">
                        <input type="number" name="lat_villages" class="form-control"/>
                    </div>
                </div>
                
                <div class="clearfix"></div>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-info" value="save"/>
            </div>
        </form> 
    </div>
</section>

@endsection

resources/views/villagesperingatan/edit.blade.php
@extends('layouts.global')
@section('content')

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Edit Data Desa</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{url ('/admin') }}">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('villages.index') }}">Data Desa</a></li>
                    <li class="breadcrumb-item active">Edit Data Desa</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<section class="content">
    <div class="container-fluid">
        <form method="POST" action="{{route('villages.update', $village->id)}}">
            @method('PUT')
            <input type="hidden" name="_token" value="{{ csrf_token()}} ">
            <div class="form-group">
                <div class="row">
                    <label class="col-md-3">Nama Desa</label>
                    <div class="col-md-6">
                        <input type="text" name="title" class="form-control" value="{{ $village->title}}"/>
                    </div>
                </div>
                
                <div class="row mt-3">
                    <label class="col-md-3">Kecamatan</label>
                    <div class="col-md-6">
                        <select type="text" name="district_id" class="form-control">
                            <option value="">Pilih Kecamatan</option>
                            @foreach ($districts as $d)
                            <option value="{{ $d -> id}}"
                                
                                @if($d->id == $village->district_id)
                                selected
                                @endif
                                
                                >{{ $d -> title}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    
                    <div class="row mt-3">
                        <label class="col-md-3">Longitude Desa</label>
                        <div class="col-md-6">
                            <input type="number" name="long_villages" 
                            class="form-control" value="{{ $village->long_villages}}"/>
                        </div>
                    </div>
                    
                    <div class="row mt-3">
                        <label class="col-md-3">Latitude Desa</label>
                        <div class="col-md-6">
                            <input type="number" name="lat_villages" 
                            class="form-control" value="{{ $village->lat_villages}}"/>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-info" value="save"/>
                </div>
            </form> 
        </div>
    </section>
    
    @endsection

resources/views/villagesperingatan/index.blade.php
@extends('layouts.global')
@section('content')

<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Halaman Desa</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{url ('/admin') }}">Dashboard</a></li>
          <li class="breadcrumb-item active">Desa</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<section class="content">
  <div class="container-fluid">
    <p>
      <a href="{{route('villages.create')}}" class="btn btn-sm btn-primary"><i class="fas fa-plus-square mr-2"></i>Tambah Data</a>
      {{-- <a href="{{ route('villages.show') }}" class="btn btn-success btn-sm ml-2"><i class="fas fa-eye mr-2"></i>Peta Desa</a>  --}}
    </p>
    <div class="row">
      <div class="col-12">
        <div class="card">
          {{-- <div class="card-header">
            <h3 class="card-title">Tabel Genangan</h3>
          </div> --}}
          <!-- /.card-header -->
          <div class="card-body table-responsive p-0">
            <table class="table table-hover text-nowrap">
              <thead>
                <tr>
                  <th>Nama Desa</th>
                  <th>Kecamatan</th>
                  <th>Riwayat Banjir</th>
                  <th>Longitude</th>
                  <th>Latitude</th>
                  <th>Aksi</th>
                </tr>
              </thead>
              <tbody>
                @if(count($villages))
                @foreach ($villages as $v)
                <tr>
                  <td>{{ $v->title}}</td>
                  <td>{{ $v->district->title}}</td>
                  <td>{{ $v->histories->count() }}</td>
                  <td>{{ $v->long_villages}}</td>
                  <td>{{ $v->lat_villages}}</td>
                  <td>
                    <a href="{{ route('villages.edit', $v->id) }}" class="btn btn-primary btn-sm"><i class="fas fa-edit mr-2"></i>Edit </a>
                    <a href="javascript:void(0)" onclick="$(this).parent().find('form').submit()" class="btn btn-secondary btn-sm"><i class="fas fa-trash-alt mr-2"></i>Delete</a>
                    <form action="{{ route('villages.destroy', $v->id) }}" method="POST">
                      @method('DELETE')
                      <input type="hidden" name="_token" value="{{ csrf_token()}} ">
                    </form>
                  </td>
                </tr>
                @endforeach
                @else
                <tr><td colspan="4">No Villages Found</td></tr>
                @endif
              </tbody>
            </table>
            {{ $villages->render() }}
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
    </div>
    
  </div>
</section>

@endsection